version: "3.5"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.1-1-ubi8
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - confluent
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  kafka:
    image: confluentinc/cp-server:7.1.1-1-ubi8
    container_name: kafka
    hostname: kafka
    networks:
      - confluent
    ports:
      - "9092:9092"
      - "9999:9999"
    volumes:
      - ./logging:/logging
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_LOG_SEGMENT_BYTES: 536870912
      KAFKA_LOG_RETENTION_BYTES: 536870912
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/logging/log4j.properties"

networks:
  confluent:
